// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * P​l​e​a​s​e​ ​n​a​v​i​g​a​t​e​ ​t​o​ ​"​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​3​0​0​1​/​:​l​o​c​a​l​e​"​,​ ​w​h​e​r​e​ ​"​:​l​o​c​a​l​e​"​ ​i​s​ ​o​n​e​ ​o​f​ ​f​o​l​l​o​w​i​n​g​:​ ​"​e​n​"​,​ ​"​d​e​"​ ​o​r​ ​"​i​t​"​ ​e​.​g​.​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​3​0​0​1​/​e​n​"​>​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​3​0​0​1​/​e​n​<​/​a​>
	 */
	INSTRUCTIONS_LOCALE: string
	/**
	 * P​l​e​a​s​e​ ​n​a​v​i​g​a​t​e​ ​t​o​ ​"​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​3​0​0​1​/​e​n​/​:​n​a​m​e​"​,​ ​w​h​e​r​e​ ​"​:​n​a​m​e​"​ ​i​s​ ​y​o​u​r​ ​n​a​m​e​ ​e​.​g​.​ ​<​a​ ​h​r​e​f​=​"​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​3​0​0​1​/​e​n​/​J​o​h​n​"​>​h​t​t​p​:​/​/​l​o​c​a​l​h​o​s​t​:​3​0​0​1​/​e​n​/​J​o​h​n​<​/​a​>
	 */
	INSTRUCTIONS_NAME: string
}

export type TranslationFunctions = {
	/**
	 * Hello {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Please navigate to "http://localhost:3001/:locale", where ":locale" is one of following: "en", "de" or "it" e.g. <a href="http://localhost:3001/en">http://localhost:3001/en</a>
	 */
	INSTRUCTIONS_LOCALE: () => LocalizedString
	/**
	 * Please navigate to "http://localhost:3001/en/:name", where ":name" is your name e.g. <a href="http://localhost:3001/en/John">http://localhost:3001/en/John</a>
	 */
	INSTRUCTIONS_NAME: () => LocalizedString
}

export type Formatters = {}
