// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * a​p​p​l​i​c​a​t​i​o​n​ ​s​t​a​r​t​e​d
	 */
	STARTUP: string
	/**
	 * c​h​o​o​s​e​ ​l​o​c​a​l​e​.​.​.
	 */
	CHOOSE_LOCALE: string
	/**
	 * R​e​c​o​m​m​e​n​d​e​d​ ​I​D​E​ ​s​e​t​u​p​:
	 */
	RECOMMENDED_SETUP: string
	/**
	 * c​o​u​n​t​ ​i​s​:​ ​{​c​o​u​n​t​}
	 * @param {number} count
	 */
	COUNT: RequiredParams<'count'>
	/**
	 * E​d​i​t​ ​<​c​o​d​e​>​{​c​o​m​p​o​n​e​n​t​}​<​/​c​o​d​e​>​ ​t​o​ ​t​e​s​t​ ​h​o​t​ ​m​o​d​u​l​e​ ​r​e​p​l​a​c​e​m​e​n​t​.
	 * @param {string} component
	 */
	EDIT: RequiredParams<'component'>
	/**
	 * T​o​d​a​y​ ​i​s​ ​{​d​a​t​e​|​w​e​e​k​d​a​y​}
	 * @param {Date} date
	 */
	TODAY: RequiredParams<'date|weekday'>
}

export type TranslationFunctions = {
	/**
	 * application started
	 */
	STARTUP: () => LocalizedString
	/**
	 * choose locale...
	 */
	CHOOSE_LOCALE: () => LocalizedString
	/**
	 * Recommended IDE setup:
	 */
	RECOMMENDED_SETUP: () => LocalizedString
	/**
	 * count is: {count}
	 */
	COUNT: (arg: { count: number }) => LocalizedString
	/**
	 * Edit <code>{component}</code> to test hot module replacement.
	 */
	EDIT: (arg: { component: string }) => LocalizedString
	/**
	 * Today is {date|weekday}
	 */
	TODAY: (arg: { date: Date }) => LocalizedString
}

export type Formatters = {
	weekday: (value: Date) => unknown
}
