// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { inject, ref } from 'vue'
import { initI18nVuePlugin } from 'typesafe-i18n/adapters/adapter-vue';
import type { Locales, Translation, TranslationFunctions, Formatters } from './i18n-types'
import { loadedLocales, loadedFormatters } from './i18n-util'

const { typesafeI18n, i18nPlugin } = initI18nVuePlugin<Locales, Translation, TranslationFunctions, Formatters>(inject, ref, loadedLocales, loadedFormatters)

export { typesafeI18n, i18nPlugin }
