// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { i18nString, i18nObject, i18n } from './i18n-util';

const L = i18n()

export { i18nString, i18nObject, L }

export default L
