// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initI18n } from './i18n-util';

export const L = initI18n()

export default L
