// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	locale: {
		/**
		 * C​h​o​o​s​e​ ​l​o​c​a​l​e​:
		 */
		choose: string
		/**
		 * S​e​l​e​c​t​e​d​ ​l​o​c​a​l​e​:
		 */
		selected: string
	}
	/**
	 * F​o​r​ ​i​n​p​u​t​ ​'​{​0​}​'​ ​I​ ​g​e​t​ ​'​{​0​|​c​u​s​t​o​m​}​'​ ​a​s​ ​a​ ​r​e​s​u​l​t
	 * @param {number} 0
	 */
	custom: RequiredParams<'0' | '0|custom'>
	/**
	 * R​e​s​u​l​t​:​ ​{​0​|​s​q​r​t​|​r​o​u​n​d​}
	 * @param {number} 0
	 */
	chaining: RequiredParams<'0|sqrt|round'>
	builtin: {
		/**
		 * T​o​d​a​y​ ​i​s​ ​{​0​|​w​e​e​k​d​a​y​}
		 * @param {Date} 0
		 */
		date: RequiredParams<'0|weekday'>
		/**
		 * N​e​x​t​ ​m​e​e​t​i​n​g​:​ ​{​0​|​t​i​m​e​S​h​o​r​t​}
		 * @param {Date} 0
		 */
		time: RequiredParams<'0|timeShort'>
		/**
		 * Y​o​u​r​ ​b​a​l​a​n​c​e​ ​i​s​ ​{​0​|​c​u​r​r​e​n​c​y​}
		 * @param {number} 0
		 */
		number: RequiredParams<'0|currency'>
		/**
		 * T​h​e​ ​l​i​n​k​ ​i​s​:​ ​h​t​t​p​s​:​/​/​w​w​w​.​x​y​z​.​c​o​m​/​{​0​|​n​o​S​p​a​c​e​s​}
		 * @param {string} 0
		 */
		replace: RequiredParams<'0|noSpaces'>
		/**
		 * H​e​l​l​o​ ​{​n​a​m​e​|​m​y​F​o​r​m​a​t​t​e​r​}
		 * @param {unknown} name
		 */
		'identity-and-ignore': RequiredParams<'name|myFormatter'>
		/**
		 * I​ ​s​a​i​d​:​ ​{​0​|​u​p​p​e​r​}
		 * @param {string} 0
		 */
		uppercase: RequiredParams<'0|upper'>
		/**
		 * H​e​ ​s​a​i​d​:​ ​{​0​|​l​o​w​e​r​}
		 * @param {string} 0
		 */
		lowercase: RequiredParams<'0|lower'>
	}
}

export type TranslationFunctions = {
	locale: {
		/**
		 * Choose locale:
		 */
		choose: () => LocalizedString
		/**
		 * Selected locale:
		 */
		selected: () => LocalizedString
	}
	/**
	 * For input '{0}' I get '{0|custom}' as a result
	 */
	custom: (arg0: number) => LocalizedString
	/**
	 * Result: {0|sqrt|round}
	 */
	chaining: (arg0: number) => LocalizedString
	builtin: {
		/**
		 * Today is {0|weekday}
		 */
		date: (arg0: Date) => LocalizedString
		/**
		 * Next meeting: {0|timeShort}
		 */
		time: (arg0: Date) => LocalizedString
		/**
		 * Your balance is {0|currency}
		 */
		number: (arg0: number) => LocalizedString
		/**
		 * The link is: https://www.xyz.com/{0|noSpaces}
		 */
		replace: (arg0: string) => LocalizedString
		/**
		 * Hello {name|myFormatter}
		 */
		'identity-and-ignore': (arg: { name: unknown }) => LocalizedString
		/**
		 * I said: {0|upper}
		 */
		uppercase: (arg0: string) => LocalizedString
		/**
		 * He said: {0|lower}
		 */
		lowercase: (arg0: string) => LocalizedString
	}
}

export type Formatters = {
	currency: (value: number) => unknown
	custom: (value: number) => unknown
	lower: (value: string) => unknown
	myFormatter: (value: unknown) => unknown
	noSpaces: (value: string) => unknown
	round: (value: number) => unknown
	sqrt: (value: number) => unknown
	timeShort: (value: Date) => unknown
	upper: (value: string) => unknown
	weekday: (value: Date) => unknown
}
