// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	locale: {
		/**
		 * Choose locale:
		 */
		choose: string
		/**
		 * Selected locale:
		 */
		selected: string
	}
	/**
	 * For input '{0}' I get '{0|custom}' as a result
	 * @param {number} 0
	 */
	custom: RequiredParams<'0' | '0|custom'>
	/**
	 * Result: {0|sqrt|round}
	 * @param {number} 0
	 */
	chaining: RequiredParams<'0|sqrt|round'>
	builtin: {
		/**
		 * Today is {0|weekday}
		 * @param {Date} 0
		 */
		date: RequiredParams<'0|weekday'>
		/**
		 * Next meeting: {0|timeShort}
		 * @param {Date} 0
		 */
		time: RequiredParams<'0|timeShort'>
		/**
		 * Your balance is {0|currency}
		 * @param {number} 0
		 */
		number: RequiredParams<'0|currency'>
		/**
		 * The link is: https://www.xyz.com/{0|noSpaces}
		 * @param {string} 0
		 */
		replace: RequiredParams<'0|noSpaces'>
		/**
		 * Hello {name|myFormatter}
		 * @param {unknown} name
		 */
		'identity-and-ignore': RequiredParams<'name|myFormatter'>
		/**
		 * I said: {0|upper}
		 * @param {string} 0
		 */
		uppercase: RequiredParams<'0|upper'>
		/**
		 * He said: {0|lower}
		 * @param {string} 0
		 */
		lowercase: RequiredParams<'0|lower'>
	}
}

export type TranslationFunctions = {
	locale: {
		/**
		 * Choose locale:
		 */
		choose: () => LocalizedString
		/**
		 * Selected locale:
		 */
		selected: () => LocalizedString
	}
	/**
	 * For input '{0}' I get '{0|custom}' as a result
	 */
	custom: (arg0: number) => LocalizedString
	/**
	 * Result: {0|sqrt|round}
	 */
	chaining: (arg0: number) => LocalizedString
	builtin: {
		/**
		 * Today is {0|weekday}
		 */
		date: (arg0: Date) => LocalizedString
		/**
		 * Next meeting: {0|timeShort}
		 */
		time: (arg0: Date) => LocalizedString
		/**
		 * Your balance is {0|currency}
		 */
		number: (arg0: number) => LocalizedString
		/**
		 * The link is: https://www.xyz.com/{0|noSpaces}
		 */
		replace: (arg0: string) => LocalizedString
		/**
		 * Hello {name|myFormatter}
		 */
		'identity-and-ignore': (arg: { name: unknown }) => LocalizedString
		/**
		 * I said: {0|upper}
		 */
		uppercase: (arg0: string) => LocalizedString
		/**
		 * He said: {0|lower}
		 */
		lowercase: (arg0: string) => LocalizedString
	}
}

export type Formatters = {
	currency: (value: number) => unknown
	custom: (value: number) => unknown
	lower: (value: string) => unknown
	myFormatter: (value: unknown) => unknown
	noSpaces: (value: string) => unknown
	round: (value: number) => unknown
	sqrt: (value: number) => unknown
	timeShort: (value: Date) => unknown
	upper: (value: string) => unknown
	weekday: (value: Date) => unknown
}
