import { writeFileIfContainsChanges } from '../file-utils'
import { GeneratorConfigWithDefaultValues } from '../generator'

const getNodeUtils = ({ utilFileName: utilFile }: GeneratorConfigWithDefaultValues) => {
	return `// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initI18n } from './${utilFile}';

export const LLL = initI18n()
`
}

export const generateNodeAdapter = async (config: GeneratorConfigWithDefaultValues): Promise<void> => {
	const { outputPath } = config

	const nodeUtils = getNodeUtils(config)

	await writeFileIfContainsChanges(outputPath, 'i18n-node', nodeUtils)
}
