import { writeFileIfContainsChanges } from '../file-utils'
import { GeneratorConfigWithDefaultValues } from '../generator'

const getSvelteUtils = (
	{ baseLocale, formattersTemplateFileName, typesFileName, utilFileName }: GeneratorConfigWithDefaultValues,
	importType: string,
) => {
	return `// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { getI18nSvelteStore } from 'typesafe-i18n';
import${importType} { Locales, Translation, TranslationFunctions, Formatters } from './${typesFileName}'
import { getTranslationForLocale } from './${utilFileName}'
import { initFormatters } from './${formattersTemplateFileName}'

const { initI18n: init, setLocale, isLoadingLocale, locale, LL } = getI18nSvelteStore<Locales, Translation, TranslationFunctions, Formatters>()

const initI18n = (locale: Locales = '${baseLocale}') => init(locale, getTranslationForLocale, initFormatters)

export { initI18n, setLocale, isLoadingLocale, locale, LL }

export default LL
`
}

export const generateSvelteAdapter = async (
	config: GeneratorConfigWithDefaultValues,
	importType: string,
): Promise<void> => {
	const { outputPath } = config

	const svelteUtils = getSvelteUtils(config, importType)

	await writeFileIfContainsChanges(outputPath, 'i18n-svelte', svelteUtils)
}
