import type { GeneratorConfigWithDefaultValues, OutputFormats } from './generate-files'
import { parseTypescriptVersion, TypescriptVersion } from './generator-util'

export const OVERRIDE_WARNING = "// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten."

type FileEnding = `.${string}`

let outputFormat: OutputFormats = 'TypeScript'
let tsVersion: TypescriptVersion = parseTypescriptVersion('4.3')

export const configureOutputHandler = (config: GeneratorConfigWithDefaultValues, version: TypescriptVersion): void => {
	outputFormat = config.outputFormat

	shouldGenerateJsDoc = outputFormat === 'JavaScript'
	fileEnding = shouldGenerateJsDoc ? '.js' : '.ts'

	tsVersion = version
	supportsTemplateLiteralTypes = (tsVersion.major === 4 && tsVersion.minor >= 1) || tsVersion.major >= 5
	supportsImportType = (tsVersion.major === 3 && tsVersion.minor >= 8) || tsVersion.major >= 4

	const importTypeStatement = `import${supportsImportType ? ' type' : ''}`
	importTypes = (from: string, ...types: string[]): string =>
		shouldGenerateJsDoc ? '' : `${importTypeStatement} { ${types.join(', ')} } from '${from}'`

	type = (type: string): string => shouldGenerateJsDoc ? '' : `: ${type}`

	generic = (generic: string): string => shouldGenerateJsDoc ? '' : `<${generic}>`
}

// --------------------------------------------------------------------------------------------------------------------

export let supportsTemplateLiteralTypes: boolean
export let supportsImportType: boolean
export let shouldGenerateJsDoc: boolean
export let fileEnding: FileEnding

// --------------------------------------------------------------------------------------------------------------------

export let importTypes: (from: string, ...types: string[]) => string

export let type: (type: string) => string

export let generic: (generic: string) => string
