// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * a​p​p​ ​s​t​a​r​t​e​d
	 */
	STARTUP: string
	/**
	 * c​h​o​o​s​e​ ​l​o​c​a​l​e​.​.​.
	 */
	CHOOSE_LOCALE: string
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * Y​o​u​r​ ​n​a​m​e​:
	 */
	YOUR_NAME: string
	/**
	 * S​e​l​e​c​t​e​d​ ​l​o​c​a​l​e​:
	 */
	SELECTED_LOCALE: string
	/**
	 * T​o​d​a​y​ ​i​s​ ​{​d​a​t​e​|​w​e​e​k​d​a​y​}
	 * @param {Date} date
	 */
	TODAY: RequiredParams<'date|weekday'>
	/**
	 * A​p​p​l​e​s
	 */
	APPLES_LABEL: string
	/**
	 * B​a​n​a​n​a​s
	 */
	BANANAS_LABEL: string
	/**
	 * I​ ​w​a​n​t​ ​t​o​ ​b​u​y​ ​{​n​r​O​f​A​p​p​l​e​s​|​f​a​l​l​b​a​c​k​0​}​ ​a​p​p​l​e​{​{​s​}​}​ ​a​n​d​ ​{​n​r​O​f​B​a​n​a​n​a​s​|​f​a​l​l​b​a​c​k​0​}​ ​b​a​n​a​n​a​{​{​s​}​}​.
	 * @param {number} nrOfApples
	 * @param {number} nrOfBananas
	 */
	FRUITS: RequiredParams<'nrOfApples|fallback0' | 'nrOfBananas|fallback0'>
}

export type TranslationFunctions = {
	/**
	 * app started
	 */
	STARTUP: () => LocalizedString
	/**
	 * choose locale...
	 */
	CHOOSE_LOCALE: () => LocalizedString
	/**
	 * Hello {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Your name:
	 */
	YOUR_NAME: () => LocalizedString
	/**
	 * Selected locale:
	 */
	SELECTED_LOCALE: () => LocalizedString
	/**
	 * Today is {date|weekday}
	 */
	TODAY: (arg: { date: Date }) => LocalizedString
	/**
	 * Apples
	 */
	APPLES_LABEL: () => LocalizedString
	/**
	 * Bananas
	 */
	BANANAS_LABEL: () => LocalizedString
	/**
	 * I want to buy {nrOfApples|fallback0} apple{{s}} and {nrOfBananas|fallback0} banana{{s}}.
	 */
	FRUITS: (arg: { nrOfApples: number, nrOfBananas: number }) => LocalizedString
}

export type Formatters = {
	fallback0: (value: number) => unknown
	weekday: (value: Date) => unknown
}
