// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'it'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * choose locale...
	 */
	CHOOSE_LOCALE: string
	/**
	 * Hello {name}!
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * Edit <code>pages/index.tsx</code> and save to reload.
	 */
	EDIT_AND_SAVE: string
	/**
	 * Learn Next.js
	 */
	LEARN_REACT: string
	/**
	 * Your name:
	 */
	YOUR_NAME: string
	/**
	 * Selected locale:
	 */
	SELECTED_LOCALE: string
	/**
	 * Today is {date|weekday}
	 * @param {Date} date
	 */
	TODAY: RequiredParams<'date|weekday'>
}

export type TranslationFunctions = {
	/**
	 * choose locale...
	 */
	CHOOSE_LOCALE: () => LocalizedString
	/**
	 * Hello {name}!
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Edit <code>pages/index.tsx</code> and save to reload.
	 */
	EDIT_AND_SAVE: () => LocalizedString
	/**
	 * Learn Next.js
	 */
	LEARN_REACT: () => LocalizedString
	/**
	 * Your name:
	 */
	YOUR_NAME: () => LocalizedString
	/**
	 * Selected locale:
	 */
	SELECTED_LOCALE: () => LocalizedString
	/**
	 * Today is {date|weekday}
	 */
	TODAY: (arg: { date: Date }) => LocalizedString
}

export type Formatters = {
	weekday: (value: Date) => unknown
}
