export { detectLocale } from './detect.mjs'
export type { LocaleDetector } from './detect.mjs'
export { documentCookieDetector, initDocumentCookieDetector } from './detectors/browser/document-cookie.mjs'
export { htmlLangAttributeDetector } from './detectors/browser/html-lang-attribute.mjs'
export { initLocalStorageDetector, localStorageDetector } from './detectors/browser/localstorage-detector.mjs'
export { navigatorDetector } from './detectors/browser/navigator.mjs'
export { initQueryStringDetector, queryStringDetector } from './detectors/browser/query-string.mjs'
export { initSessionStorageDetector, sessionStorageDetector } from './detectors/browser/sessionstorage-detector.mjs'
export { initAcceptLanguageHeaderDetector } from './detectors/server/accept-language-header.mjs'
export { initRequestCookiesDetector } from './detectors/server/request-cookies.mjs'
export { initRequestHostnameDetector } from './detectors/server/request-hostname.mjs'
export { initRequestParametersDetector } from './detectors/server/request-parameters.mjs'

