name: '@typesafe-i18n/importer example - update dependencies'

on:
   schedule:
      - cron: '0 0 * * 1' # Runs at 00:00 on Monday
   workflow_dispatch:

defaults:
   run:
      working-directory: packages/importer/example

jobs:
   check-importer:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - name: install node
           uses: actions/setup-node@v2
           with:
              node-version: 16.14.0

         - name: install dependencies
           run: npm install --no-save

         - name: update all dependencies
           run: npm up

         - name: run import
           run: npm run i18n:import

         - name: run TypeScript compiler
           run: tsc --noEmit

         - name: Create Pull Request
           uses: peter-evans/create-pull-request@v3
           with:
              token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              branch: update/importer-dependencies
              commit-message: 'chore: update `@typesafe-i18n/importer` example dependencies'
              title: 'chore: update `@typesafe-i18n/importer` example dependencies'
              body: >
                 This PR is auto-generated by a GitHub action.
