name: '@typesafe-i18n/formatters example - update dependencies'

on:
   schedule:
      - cron: '0 20 * * 0' # Runs at 20:00 on Sunday
   workflow_dispatch:

defaults:
   run:
      working-directory: packages/formatters/example

jobs:
   check-formatters:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3

         - name: install node
           uses: actions/setup-node@v2
           with:
              node-version: 18.16.1

         - name: install dependencies
           run: npm install --no-save

         - name: update all dependencies
           run: npm up

         - name: run generator
           run: npm run typesafe-i18n -- --no-watch

         - name: run TypeScript compiler
           run: tsc --noEmit

         - name: run build
           run: npm run build

         - name: Create Pull Request
           uses: peter-evans/create-pull-request@v3
           with:
              token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
              branch: update/formatters-dependencies
              commit-message: 'chore: update `@typesafe-i18n/formatters` example dependencies'
              title: 'chore: update `@typesafe-i18n/formatters` example dependencies'
              body: >
                 This PR is auto-generated by a GitHub action.
