name: check markdown links

on:
   pull_request:
      branches:
         - 'main'

jobs:
   check:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2

         - uses: pnpm/action-setup@v2
           with:
              version: 7.5.2

         - name: install node
           uses: actions/setup-node@v2
           with:
              node-version: 16.14.0
              cache: 'pnpm'

         - run: pnpm install --no-save

         - name: run link checks
           run: pnpm markdown-link-check
